name: AutoDeploy

on:
  push:
    branches:
      - 'dev'
      - 'master'

jobs:
  build:
    name: "Сборка проекта под Android 🔨"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21'

    - name: Install pnpm
      run: npm -g i pnpm

    - name: Install dependencies
      run: pnpm i

    - name: Build web assets
      run: pnpm build

    - name: Add Capacitor Android project
      run: npx cap add android

    - name: Sync Capacitor project
      run: npx cap sync

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Accept Android SDK licenses
      run: |
        yes | sdkmanager --licenses

    - name: Build Android APK
      working-directory: android
      run: ./gradlew assembleRelease

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v3
      with:
        name: android-release-apk
        path: android/app/build/outputs/apk/release/app-release.apk

  deploy_dev:
    name: "Уведомление в Telegram 🔔"
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Escape bad symbols in variables
        id: escape_vars
        run: |
          escaped_message=$(echo "${{ github.event.head_commit.message }}" | perl -pe 's/([&~\`\*\_\[\]()#\+\-\=\|\{\}\.\!])/\\\\$1/g')
          escaped_actor=$(echo "${{ github.actor }}" | perl -pe 's/([&~\`\*\_\[\]()#\+\-\=\|\{\}\.\!])/\\\\$1/g')
          escaped_branch=$(echo "${{ github.ref_name }}" | perl -pe 's/([&~\`\*\_\[\]()#\+\-\=\|\{\}\.\!])/\\\\$1/g')
          echo "escaped_message=$escaped_message" >> $GITHUB_ENV
          echo "escaped_actor=$escaped_actor" >> $GITHUB_ENV
          echo "escaped_branch=$escaped_branch" >> $GITHUB_ENV

      - name: Send Telegram Message
        run: |
          curl \
            --data-urlencode 'chat_id=${{ secrets.TELEGRAM_CHAT_ID }}' \
            --data-urlencode 'message_thread_id=${{ secrets.TELEGRAM_MESSAGE_THREAD_ID }}' \
            --data-urlencode 'link_preview_options={"url":"${{ github.event.head_commit.url }}"}' \
            --data-urlencode 'parse_mode=markdownv2' \
            --data-urlencode $'text=🔨 *Frontend deploy* 🔨\n\n>${{ env.escaped_message }}\n_by [${{ env.escaped_actor }}](https://github.com/${{ env.escaped_actor }})_ at `${{ env.escaped_branch }}`\n\n[commit link](${{ github.event.head_commit.url }})' \
            curl "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage"
