on:
  push:
    branches:
      - master

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Semantic Release
        with:
            node-version: '20'
            run: npx semantic-release -p @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/npm @semantic-release/github --branches master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
