on:
  push:
    branches:
      - master
      - dev

jobs:
  semantic-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js 21
        uses: actions/setup-node@v3
        with:
          node-version: '21'
      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
