on:
  push:
    branches:
      - master

jobs:
  semantic-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js 21
        uses: actions/setup-node@v3
        with:
          node-version: '21'
      - name: Install @semantic-release/changelog
        run: npm i @semantic-release/changelog
      - name: Semantic Release
        run: npx semantic-release -p @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/npm @semantic-release/github --branches master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
